config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "dashboards#index"
  resources :controls
  resources :misc_reagents
  resources :chem_reagents
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chem_reagent.rb
class ChemReagent < ApplicationRecord
  before_save {self.reagent = reagent.upcase}
  before_save {self.lot = lot.upcase}
  
  validates :reagent, presence: true
  validates :lot, presence: true
  validates :start, presence: true
  validates :expiration, presence: true
  validates :flex, presence: true
  validates :box, presence: true
end

app/models/control.rb
class Control < ApplicationRecord
  before_save {self.name = name.upcase}
  before_save {self.lot = lot.upcase}
  before_save {self.item = item.titleize}
  
  
  validates :name, presence: true
  validates :item, presence: true
  validates :lot, presence: true
  validates :start, presence: true
  validates :expiration, presence: true
  validates :stock, presence: true
  
  default_scope { order(name: :asc) }
end

app/models/misc_reagent.rb
class MiscReagent < ApplicationRecord
  before_save {self.kit = kit.capitalize}
  before_save {self.lot = lot.upcase}
  
  validates :kit, presence: true
  validates :lot, presence: true
  validates :start, presence: true
  validates :expiration, presence: true
  validates :test_left, presence: true
  validates :box, presence: true
  
  default_scope { order(kit: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chem_reagents_controller.rb
class ChemReagentsController < ApplicationController
  def index
    @chem_reagents = ChemReagent.all
  end
  
  def new
    @chem_reagent = ChemReagent.new
  end
  
  def create
    @chem_reagent = ChemReagent.new(chem_reagent_params)
    if  @chem_reagent.save
      flash[:notice] = "Reagent Saved"
      redirect_to @chem_reagent
    else
      flash.now[:alert] = "Reagent failed to saved"
      render 'new'
    end
  end
  
  def destroy
    @chem_reagent = ChemReagent.find(params[:id])
    if @chem_reagent.destroy
      flash[:notice] = "Reagent has been deleted"
      redirect_to chem_reagents_path
    end
  end
  
  def edit
    @chem_reagent = ChemReagent.find(params[:id])
  end
  
  def update
    @chem_reagent = ChemReagent.find(params[:id])
    if @chem_reagent.update(chem_reagent_params)
       flash[:notice] = "Reagents updated"
       redirect_to chem_reagents_path
    else
       flash.now[:alert] = "Failed to update reagent"
       render :edit
    end
  end
  
  def show
    @chem_reagent = ChemReagent.find(params[:id])
  end
  
  private
  def chem_reagent_params
    params.require(:chem_reagent).permit(:reagent, :lot, :start, :expiration, :flex, :box)
  end
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_control, only: [:show, :edit, :update, :destroy]
  def index
    @controls = Control.all
  end
  
  def new
    @control = Control.new
  end
  
  def create
    @control = Control.new(control_params)
      if @control.save
        flash[:notice] = "Control Saved"
        redirect_to @control
      else
        flash.now[:alert] = "Control failed to saved"
        render :new
      end 
  end
  
  def show
    
  end
  
  def edit
    
  end
  
  def update
     
     if @control.update(control_params)
       flash[:notice] = "Controls updated"
       redirect_to controls_path
     else
       flash.now[:alert] = "Failed to update control"
       render :edit
     end
  end
  
  def destroy
    @control = Control.find(params[:id])
    if @control.destroy
      flash[:notice] = "Control has been deleted"
      redirect_to controls_path
    end
  end
  
  private
  
  def set_control
    @control = Control.find(params[:id])
  end
  
  def control_params
    params.require(:control).permit(:name, :lot, :start, :expiration, :item, :stock)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @chem_reagents = ChemReagent.all
    @controls = Control.all
    @misc_reagents = MiscReagent.all
  end
end

app/controllers/misc_reagents_controller.rb
class MiscReagentsController < ApplicationController
  def index
    @misc_reagents = MiscReagent.all
  end
  
  def new
    @misc_reagent = MiscReagent.new
  end

  def create
    @misc_reagent = MiscReagent.new(misc_reagent_params)
    if  @misc_reagent.save
      flash[:notice] = "Miscellaneous Reagent Saved"
      redirect_to @misc_reagent
    else
      flash.now[:alert] = " Reagent failed to saved"
      render 'new'
    end
  end
  
  def show
    @misc_reagent = MiscReagent.find(params[:id])
  end
  
  def destroy
    @misc_reagent = MiscReagent.find(params[:id])
    if @misc_reagent.destroy
      flash[:notice] = "Reagent has been deleted"
      redirect_to misc_reagents_path
    end
  end
  
  def edit
    @misc_reagent = MiscReagent.find(params[:id])
  end
  
  def update
    @misc_reagent = MiscReagent.find(params[:id])
    if @misc_reagent.update(misc_reagent_params)
       flash[:notice] = "Reagents updated"
       redirect_to misc_reagents_path
    else
       flash.now[:alert] = "Failed to update reagent"
       render :edit
    end
  end
  
  private
  
  def misc_reagent_params
    params.require(:misc_reagent).permit(:kit, :lot, :start, :expiration, :test_left, :box)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cap_name
    current_user.email.split('@').first.capitalize
  end
end

app/views/chem_reagents/_form.html.erb
<div class="col-md-offset-3 col-md-6 well ">
  <%= render 'shared/errors', obj: @chem_reagent %>
    
    <%= form_for @chem_reagent do |f| %>
        <div class="field form-group">
            <%= f.label(:reagent, "Reagent") %>
            <%= f.text_field :reagent, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f. label(:lot, "Lot number") %>
            <%= f.text_field :lot, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f.label(:start, "Started On") %>
            <%= f.text_field :start, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f.label(:expiration, "Expiration") %>
            <%= f. text_field :expiration, autofocus: true, class: 'form-control'  %>
        <div>
        
        <div class="field form-group">
            <%= f. label(:flex, "Flex (open box)") %>
            <%= f.text_field :flex, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f. label(:box, "Box)") %>
            <%= f.text_field :box, autofocus: true, class: 'form-control' %>
        </div>
        
        <br />
        <div class="actions form-group">
            <%= f.submit(@chem_reagent.new_record? ? "Create Reagent" : "Update", class: 'btn btn-success') %>
        </div>
    <% end %>

    <%= link_to "Back", chem_reagents_path, class: 'btn btn-info' %>
</div>

app/views/chem_reagents/edit.html.erb
<h1>Edit Chem reagent</h1>

<%= render 'form' %>

app/views/chem_reagents/index.html.erb
<div class="row"> 

<h3 class = "text-center">Chemistry Reagents</h3>

  <div class="col-md-offset-1 col-md-10 col-xs-18">
    <% if @chem_reagents.empty? %>
      <h1 id="no-chem_reagents">No Chem Reagents Created</h1>
    <% else %>
      <table class="table">
        <tr>
          <th>Reagent</th>
          <th>Lot</th>
          <th>Start</th>
          <th>Expiration</th>
          <th>Flex</th>
          <th>Box</th>
          <% if user_signed_in? %>
          <th class = "text-center">Action</th>
          <th class = "text-center">Action</th>
          <% end %>
        </tr>
        
        <% @chem_reagents.each do |chem_reagent| %>
          <tr class ="<%= chem_reagent.box == 0 || (chem_reagent.expiration.to_date - Date.today).to_i <= 30 ? 'low' : 'okay' %>">
            <td><strong><%= chem_reagent.reagent%> </strong>
              <br />
              <span><small>Updated: <%= time_ago_in_words(chem_reagent.updated_at) %> ago</small></span>
            </td>
            <td><%= chem_reagent.lot %></td>
            <td><%= chem_reagent.start %></td>
            <td><%= distance_of_time_in_words_to_now(chem_reagent.expiration)%> left</td>
            <td><%= chem_reagent.flex %></td>
            <td><%= chem_reagent.box %></td>
            
            <% if user_signed_in? %>
            <td class ="text-center"><%= link_to edit_chem_reagent_path(chem_reagent), class: 'btn btn-primary btn-sm' do %> 
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    <% end %>
            </td>
            <% end %>
            
            <% if user_signed_in? %>
            <td class="text-center"><%= link_to chem_reagent_path(chem_reagent),
                                        class: 'btn btn-danger btn-sm',
                                        method: :delete,
                                        data: { confirm: 'Are you sure?' } do %> 
                                          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        <% end %>
                                        </td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>
    <br />
    <% if user_signed_in? %>
      <%= link_to  "New Chem Reagent", new_chem_reagent_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
  
</div>
  

app/views/chem_reagents/new.html.erb
<h3 class= "text-center">New Chem reagent</h3>

<%= render 'form' %>

app/views/chem_reagents/show.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h3 class= "text-center light-green"><%= @chem_reagent.reagent %></h3>
    <ul class="list-group">
      <li class="list-group-item light-gray">Lot: <%= @chem_reagent.lot %></li>
      <li class="list-group-item light-gray">Start Date: <%= @chem_reagent.start %></li>
      <li class="list-group-item light-gray">Expiration: <%= @chem_reagent.expiration %></li>
      <li class="list-group-item light-gray">Flex: <%= @chem_reagent.flex %> </li>
      <li class="list-group-item light-gray">Box: <%= @chem_reagent.box %></li>
    </ul>
  </div>
</div>

app/views/controls/_form.html.erb
<div class="col-md-offset-3 col-md-6 well ">
    <%= render 'shared/errors', obj: @control %>
    <br />
    <%= form_for @control do |f| %>
        <div class="field form-group">
            <%= f.label(:name, "QC name") %>
            <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f.label(:item, "Item") %>
            <%= f.text_field :item, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f. label(:lot, "Lot number") %>
            <%= f.text_field :lot, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f.label(:start, "Started On") %>
            <%= f.text_field :start, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f.label(:expiration, "Expiration") %>
            <%= f. text_field :expiration, autofocus: true, class: 'form-control'  %>
        <div>
        
        <div class="field form-group">
            <%= f. label(:stock, "In Stock") %>
            <%= f.text_field :stock, autofocus: true, class: 'form-control' %>
        </div>
        
        <br />
        <div class="actions form-group">
            <%= f.submit(@control.new_record? ? "Create Control" : "Update", class: 'btn btn-success') %>
        </div>
    <% end %>

    <%= link_to "Back", controls_path, class: 'btn btn-info' %>
</div>

app/views/controls/edit.html.erb
<h1 class= "text-center">Edit control</h1>

<%= render 'form' %>

app/views/controls/index.html.erb
<h3 class = "text-center">Controls</h3>

<div class="row">  
  <div class="col-md-offset-1 col-md-10 col-xs-18">
    <% if @controls.empty? %>
      <h1 id="no-controls">No Controls Created</h1>
    <% else %>
      <table class="table">
        <tr>
          <th>QC Name</th>
          <th>Item</th>
          <th>Lot number</th>
          <th>Date Started</th>
          <th>Expiration</th>
          <th>In Stock</th>
          <% if user_signed_in? %>
          <th class = "text-center">Action</th>
          <th class = "text-center">Action</th>
          <% end %>
        </tr>
        
        <% @controls.each do |control| %>
          <tr class ="<%= control.stock < 5 ? 'low' : 'okay' %>">
            <td><%= control.name %>
              <br />
              <span><small>Updated: <%= time_ago_in_words(control.updated_at) %> ago</small></span>
            </td>
            <td><%= control.item %></td>
            <td><%= control.lot %></td>
            <td><%= control.start %></td>
            <td><%= distance_of_time_in_words_to_now(control.expiration)%> left</td>
            <td class="text-center"><%= control.stock %></td>
            <% if user_signed_in? %>
            <td class ="text-center"><%= link_to edit_control_path(control), class: 'btn btn-primary btn-sm' do %>
                                      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    <% end %>
                                    </td>
                                    <td><%= link_to control_path(control),
                                            class: 'btn btn-danger btn-sm',
                                            method: :delete,
                                            data: { confirm: 'Are you sure?' } do %>
                                              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                            <% end %>
                                            </td>
            <% end %>                                                                              
          </tr>
        <% end %>
      </table>
    <% end %>
    <br />
    <% if user_signed_in? %>
      <%= link_to  "New Control", new_control_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
  
</div>
  

app/views/controls/new.html.erb
<%= render 'form' %>

app/views/controls/show.html.erb
<div class="col-md-offset-3 col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @control.name %></h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
        <li class="list-group-item"><strong>Start Date:</strong> <%= @control.start %></li>
        <li class="list-group-item"><strong>Expiration:</strong> <%= @control.expiration %></li>
        <li class="list-group-item"><strong>Lot number:</strong> <%= @control.lot %></li>
      </ul>
      
      <%= link_to  "New Control", new_control_path, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<div class="jumbotron">
  <h3>SUMMARY OF LOW REAGENTS</h3>
  <ul class="list-group">
  <% @chem_reagents.each do |chem_reagent| %>
    <% if chem_reagent.box == 0 %>
       <li class="list-group-item"><%= chem_reagent.reagent %> has no more box left</li> 
    <% end %>
    
    <% if (chem_reagent.expiration.to_date - Date.today).to_i <= 30 %>
       <li class="list-group-item"><%= chem_reagent.reagent %> has <%= distance_of_time_in_words_to_now(chem_reagent.expiration) %> before expiration</li> 
    <% end %>
  <% end %>
  
  <% @controls.each do |control| %>
    <% if control.stock < 5 %>
       <li class="list-group-item"><%= control.name %> has less than 5 in stocks</li> 
    <% end %>
    
    <% if (control.expiration.to_date - Date.today).to_i <= 30 %>
       <li class="list-group-item"><%= control.name %> has <%= distance_of_time_in_words_to_now(control.expiration) %> before expiration</li> 
    <% end %>
  <% end %>
  
  <% @misc_reagents.each do|misc_reagent| %>
    <% if misc_reagent.box == 0 %>
       <li class="list-group-item"><%= misc_reagent.kit %> has no more box left</li> 
    <% end %>
    <% if (misc_reagent.expiration.to_date - Date.today).to_i <= 30 %>
       <li class="list-group-item"><%= misc_reagent.kit %> has <%= distance_of_time_in_words_to_now(misc_reagent.expiration) %> before expiration</li> 
    <% end %>
  <% end %>
  </ul>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  
  
  
  <body>
    <%= render 'shared/header'%>
    <%= render 'shared/main' %>
    <br />
    <hr />
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/misc_reagents/_form.html.erb
<div class="col-md-offset-3 col-md-6 well ">
    
    <%= form_for @misc_reagent do |f| %>
        <div class="field form-group">
            <%= f.label(:kit, "Kit") %>
            <%= f.text_field :kit, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f. label(:lot, "Lot number") %>
            <%= f.text_field :lot, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f.label(:start, "Started On") %>
            <%= f.text_field :start, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f.label(:expiration, "Expiration") %>
            <%= f. text_field :expiration, autofocus: true, class: 'form-control'  %>
        <div>
        
        <div class="field form-group">
            <%= f. label(:test_left, "Test left(open box)") %>
            <%= f.text_field :test_left, autofocus: true, class: 'form-control' %>
        </div>
        
        <div class="field form-group">
            <%= f. label(:box, "Box)") %>
            <%= f.text_field :box, autofocus: true, class: 'form-control' %>
        </div>
        
        <br />
        <div class="actions form-group">
            <%= f.submit(@misc_reagent.new_record? ? "Create Reagent" : "Update", class: 'btn btn-success') %>
        </div>
    <% end %>

    <%= link_to "Back", misc_reagents_path, class: 'btn btn-info' %>
</div>

app/views/misc_reagents/edit.html.erb
<h1>Edit Misc reagent</h1>

<%= render 'form' %>

app/views/misc_reagents/index.html.erb
<h1 class= text-center>Miscellaneous Reagents</h1>
  <div class="row">
    
    
    
      <% @misc_reagents.each do |misc_reagent| %>
      <div class="col-md-3">
      
        <ul class="list-group">
      
        <li class="list-group-item light-green"><strong><%= misc_reagent.kit %></strong></li>
        <li class="list-group-item light-green"><span><i>Updated <%= time_ago_in_words(misc_reagent.updated_at)%> ago</small></i></span> </li>
        <li class="list-group-item <%= misc_reagent.box == 0? 'low' : 'salmon'%>">Lot: <%= misc_reagent.lot %></li>
        <li class="list-group-item <%= misc_reagent.box == 0? 'low' : 'salmon'%>">Start: <%= misc_reagent.start %></li>
        <li class="list-group-item <%= misc_reagent.box == 0? 'low' : 'salmon'%>">Expiration: <%=  distance_of_time_in_words_to_now(misc_reagent.expiration) %> left</li>
        <li class="list-group-item <%= misc_reagent.box == 0? 'low' : 'salmon'%>">Test Left: <span><small><em>(Open box)</em></small></span> <%= misc_reagent.test_left %></li>
        <li class="list-group-item <%= misc_reagent.box == 0? 'low' : 'salmon'%>">Box: <%= misc_reagent.box %></li>
        <% if user_signed_in? %>
        <li class="list-group-item"><%= link_to "Delete", misc_reagent_path(misc_reagent), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>  |  
        <%= link_to "Edit", edit_misc_reagent_path(misc_reagent), class: 'btn btn-primary'%></li>
        <% end %>
      </ul>
      
      
      
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
  <%= link_to  "New Misc Reagents", new_misc_reagent_path, class: 'btn btn-primary' %>
  <% end %>

app/views/misc_reagents/new.html.erb
<h1>New Misc reagent</h1>

<%= render 'form' %>

app/views/misc_reagents/show.html.erb
<div class="row ">
  <h3 class= "text-center"> <%= @misc_reagent.kit %> Reagent</h3>
      
    <div class="col-md-offset-3 col-md-6 ">
      <ul class="list-group">
        <li class="list-group-item rustic-light"><strong>Kit : </strong><%= @misc_reagent.kit %></li>
        <li class="list-group-item rustic-light"><strong>Lot : </strong><%= @misc_reagent.lot %></li>
        <li class="list-group-item rustic-light"><strong>Start : </strong><%= @misc_reagent.start %></li>
        <li class="list-group-item rustic-light"><strong>Expiration : </strong><%= @misc_reagent.expiration %></li>
        <li class="list-group-item rustic-light"><strong>Test Left :</strong> <small><em>(Open box)</em></small><%= @misc_reagent.test_left %></li>
        <li class="list-group-item rustic-light"><strong>Box:</strong> <%= @misc_reagent.box %></li>
      </ul>
    </div>
    
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this control from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <div class="row text-center">
      <footer role="contentinfo">
        <p><small>Copyright &copy; Erlan Rey Biyok</small></p>
      </footer>
    </div>
  </div>
</nav>

app/views/shared/_header.html.erb
<header role="banner">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button"
            class="navbar-toggle"
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Laboratory", root_path, class: "navbar-brand" %>
        </div>
  
        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1"> 
          <ul class="nav navbar-nav">
            <li ><%= link_to "Home", root_path %></li>
            <li ><%= link_to "Controls", controls_path %></li>
            <li ><%= link_to "Misc Reagents", misc_reagents_path %></li>
            <li ><%= link_to "Chem Reagents", chem_reagents_path %></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <% unless user_signed_in? %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% else %>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <li id ="rightuser">Signed in as <strong><%= cap_name %> </strong></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

app/views/shared/_main.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key == 'notice'?  'success' : 'danger' %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>  
</div>